name: .NET 8 Continuous Integration with GitHub, GitHub Actions and NuGet packages

env:
  SLN_DIR: ./RH.HATEOAS/
  CSPROJ_DIR: ./RH.HATEOAS/
  CSPROJ_FILE: RH.HATEOAS.csproj

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: |
        cd $SLN_DIR
        dotnet restore
        
    - name: Build
      run: |
        cd $SLN_DIR
        dotnet build --no-restore
        
    - name: Change .csproj version
      run: |
        cd $CSPROJ_DIR
        # Increment version in your project file (e.g., .csproj)
        # Replace the placeholder with your actual project file name
        CURRENT_VERSION=$(grep -oP '<Version>\K[^<]+' $CSPROJ_FILE)
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF+=1; OFS="."; print $0}')
        # Replace spaces with dots
        NEW_VERSION=$(echo $NEW_VERSION | tr ' ' '.')
        # Update the version in the project file
        sed -i "s|<Version>$CURRENT_VERSION</Version>|<Version>$NEW_VERSION</Version>|" $CSPROJ_FILE
        
        # Commit the version change
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Increment version to $NEW_VERSION"  -a
        git push
        
    - name: Generate release
      run: |
        cd $SLN_DIR
        dotnet build -c release

    - name: Generate NuGet package
      run: |
        cd $SLN_DIR
        dotnet pack -c release -o ../dist/

    - name: Push NuGet package
      run: dotnet nuget push "./dist/*" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json